name: Deploy Vue App

on:
  push:
    branches:
      - main  # Change to your default branch if needed

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build Vue app
      run: npm run build

    - name: Deploy to GitHub Pages
      run: npm run deploy
